services:
  mysql:
    image: mysql:8.0
    container_name: raquel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - raquel-mysql-data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  raquel-mysql-data:
